version: '3.8'

services:
  frontend:
    build: ./frontend/Present
    networks:
      - app-network

  backend:
    build: ./backend
    networks:
      - app-network
    volumes:
      - ./backend:/app

  nginx:
    build: ./nginx
    ports:
      - "8000:80"  # 瀏覽器打 http://localhost:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
