import os

ENV_STORAGE_ENDPOINT = os.getenv("STORAGE_ENDPOINT", "storage.demo01.footprint-ai.com")
ENV_STORAGE_BUCKET_NAME = os.getenv("STORAGE_BUCKET_NAME", "")
ENV_STORAGE_ACCESS_KEY = os.getenv("STORAGE_ACCESS_KEY", "")
ENV_STORAGE_ACCESS_SECRET = os.getenv("STORAGE_ACCESS_SECRET", "")
